site_name: Caddy Defender Docs
theme: material
repo_url: https://github.com/JasonLovesDoggo/caddy-defender
site_url: https://defender.jasonlovesdoggo.dev
site_description: The Caddy Defender documentation site.
site_author: Jason Cameron
nav:
  - Home: index.md
  - Getting Started: intro.md
  - Installation: installation.md
  - Configuration: config.md
  - Advanced Usage: advanced.md
  - Examples: examples.md
  - Fetchers: fetchers.md
  - Contributing: CONTRIBUTING.md
